@echo off
REM Refer to https://data.binance.vision/?prefix=data/futures/um/monthly/
SET START_DATE=2017-01-01
SET END_DATE=2021-10-15

REM USDC List
SET SHELL_CMD=python download-kline.py -s BTCUSDC ETHUSDC ADAUSDC BNBUSDC XRPUSDC ATOMUSDC TRXUSDC LINKUSDC LTCUSDC EOSUSDC SOLUSDC BCHUSDC NEOUSDC ZECUSDC BTTUSDC WINUSDC -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List
SET SHELL_CMD=python download-kline.py -s BTCUSDT ETHUSDT BUSDUSDT SOLUSDT AVAXUSDT ADAUSDT DOTUSDT BNBUSDT XRPUSDT FILUSDT LUNAUSDT ATOMUSDT FTMUSDT DYDXUSDT GALAUSDT DOGEUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%