@echo off
REM Refer to https://data.binance.vision/?prefix=data/futures/um/monthly/
SET START_DATE=2017-01-01
SET END_DATE=2021-11-01

REM USDC List
SET SHELL_CMD=python download-kline.py -s BTCUSDC ETHUSDC ADAUSDC BNBUSDC XRPUSDC ATOMUSDC TRXUSDC LINKUSDC LTCUSDC EOSUSDC SOLUSDC BCHUSDC NEOUSDC ZECUSDC BTTUSDC WINUSDC -i 1m 15m 1h 4h -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List #1
SET SHELL_CMD=python download-kline.py -s BTCUSDT ETHUSDT BUSDUSDT SOLUSDT AVAXUSDT ADAUSDT DOTUSDT BNBUSDT XRPUSDT FILUSDT LUNAUSDT ATOMUSDT FTMUSDT DYDXUSDT GALAUSDT DOGEUSDT -i 1m 15m 1h 4h -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List #2
SET SHELL_CMD=python download-kline.py -s BUSDUSDT KEYUSDT ADADOWNUSDT CKBUSDT IOSTUSDT REEFUSDT VTHOUSDT SCUSDT ONEUSDT FORUSDT XRPUSDT RSRUSDT MFTUSDT IOTXUSDT BTCDOWNUSDT COTIUSDT -i 1m 15m 1h 4h -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

SET SHELL_CMD=python merge-monthly-with-daily-files.py
echo %SHELL_CMD%
%SHELL_CMD%
