@echo off
REM Refer to https://data.binance.vision/?prefix=data/futures/um/monthly/
REM SET SHELL_CMD=python download-kline.py -s BTCUSDC EOSUSDC ETHUSDC XRPUSDC BNBUSDC ADAUSDC ATOMUSDC SOLUSDC LTCUSDC BCHUSDC LINKUSDC TRXUSDC -i 1m -startDate %START_DATE% -endDate %END_DATE%
REM echo %SHELL_CMD%
REM %SHELL_CMD%

SET START_DATE=2017-10-01
SET END_DATE=2021-10-01

REM Sanity Test
REM USDC List
REM SET SHELL_CMD=python download-kline.py -s ADAUSDC -i 1m -startDate %START_DATE% -endDate %END_DATE%
REM echo %SHELL_CMD%
REM %SHELL_CMD%

REM EXIT

REM USDC List
SET SHELL_CMD=python download-kline.py -s ADAUSDC ALGOUSDC ANKRUSDC ATOMUSDC BATUSDC BCHABCUSDC BCHSVUSDC BCHUSDC BCPTUSDC BGBPUSDC BNBUSDC BTCUSDC BTTUSDC DOGEUSDC DUSKUSDC EOSUSDC ERDUSDC ETCUSDC ETHUSDC FTMUSDC GTOUSDC LINKUSDC LTCUSDC NEOUSDC NPXSUSDC ONEUSDC ONTUSDC PERLUSDC PHBUSDC SOLUSDC TFUELUSDC TOMOUSDC TRXUSDC WAVESUSDC WINUSDC XLMUSDC XRPUSDC ZECUSDC -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet 1 to A
SET SHELL_CMD=python download-kline.py -s 1INCHDOWNUSDT 1INCHUPUSDT 1INCHUSDT AAVEDOWNUSDT AAVEUPUSDT AAVEUSDT ACMUSDT ADADOWNUSDT ADAUPUSDT ADAUSDT AGLDUSDT AIONUSDT AKROUSDT ALGOUSDT ALICEUSDT ALPACAUSDT ALPHAUSDT ANKRUSDT ANTUSDT ARDRUSDT ARPAUSDT ARUSDT ASRUSDT ATAUSDT ATMUSDT ATOMUSDT AUDIOUSDT AUDUSDT AUTOUSDT AVAUSDT AVAXUSDT AXSUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet B
SET SHELL_CMD=python download-kline.py -s BADGERUSDT BAKEUSDT BALUSDT BANDUSDT BARUSDT BATUSDT BCCUSDT BCHABCUSDT BCHDOWNUSDT BCHSVUSDT BCHUPUSDT BCHUSDT BEAMUSDT BEARUSDT BELUSDT BKRWUSDT BLZUSDT BNBBEARUSDT BNBBULLUSDT BNBDOWNUSDT BNBUPUSDT BNBUSDT BNTUSDT BONDUSDT BTCDOWNUSDT BTCSTUSDT BTCUPUSDT BTCUSDT BTGUSDT BTSUSDT BTTUSDT BULLUSDT BURGERUSDT BUSDTRY BUSDUSDT BZRXUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet C to E
SET SHELL_CMD=python download-kline.py -s C98USDT CAKEUSDT CELOUSDT CELRUSDT CFXUSDT CHRUSDT CHZUSDT CKBUSDT CLVUSDT COCOSUSDT COMPUSDT COSUSDT COTIUSDT CRVUSDT CTKUSDT CTSIUSDT CTXCUSDT CVCUSDT CVPUSDT DAIUSDT DASHUSDT DATAUSDT DCRUSDT DEGOUSDT DENTUSDT DEXEUSDT DFUSDT DGBUSDT DIAUSDT DNTUSDT DOCKUSDT DODOUSDT DOGEUSDT DOTDOWNUSDT DOTUPUSDT DOTUSDT DREPUSDT DUSKUSDT DYDXUSDT EGLDUSDT ELFUSDT ENJUSDT EOSBEARUSDT EOSBULLUSDT EOSDOWNUSDT EOSUPUSDT EOSUSDT EPSUSDT ERDUSDT ERNUSDT ETCUSDT ETHBEARUSDT ETHBULLUSDT ETHDOWNUSDT ETHUPUSDT ETHUSDT EURUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet F to L
SET SHELL_CMD=python download-kline.py -s FARMUSDT FETUSDT FIDAUSDT FILDOWNUSDT FILUPUSDT FILUSDT FIOUSDT FIROUSDT FISUSDT FLMUSDT FLOWUSDT FORTHUSDT FORUSDT FRONTUSDT FTMUSDT FTTUSDT FUNUSDT GALAUSDT GBPUSDT GHSTUSDT GNOUSDT GRTUSDT GTCUSDT GTOUSDT GXSUSDT HARDUSDT HBARUSDT HCUSDT HIVEUSDT HNTUSDT HOTUSDT ICPUSDT ICXUSDT IDEXUSDT ILVUSDT INJUSDT IOSTUSDT IOTAUSDT IOTXUSDT IRISUSDT JSTUSDT JUVUSDT KAVAUSDT KEEPUSDT KEYUSDT KLAYUSDT KMDUSDT KNCUSDT KSMUSDT LENDUSDT LINAUSDT LINKDOWNUSDT LINKUPUSDT LINKUSDT LITUSDT LPTUSDT LRCUSDT LSKUSDT LTCDOWNUSDT LTCUPUSDT LTCUSDT LTOUSDT LUNAUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet M to R
SET SHELL_CMD=python download-kline.py -s MANAUSDT MASKUSDT MATICUSDT MBLUSDT MBOXUSDT MCOUSDT MDTUSDT MDXUSDT MFTUSDT MINAUSDT MIRUSDT MITHUSDT MKRUSDT MLNUSDT MTLUSDT NANOUSDT NBSUSDT NEARUSDT NEOUSDT NKNUSDT NMRUSDT NPXSUSDT NULSUSDT NUUSDT OCEANUSDT OGNUSDT OGUSDT OMGUSDT OMUSDT ONEUSDT ONGUSDT ONTUSDT ORNUSDT OXTUSDT PAXGUSDT PAXUSDT PERLUSDT PERPUSDT PHAUSDT PNTUSDT POLSUSDT POLYUSDT PONDUSDT PSGUSDT PUNDIXUSDT QNTUSDT QTUMUSDT QUICKUSDT RADUSDT RAMPUSDT RAYUSDT REEFUSDT RENUSDT REPUSDT REQUSDT RIFUSDT RLCUSDT ROSEUSDT RSRUSDT RUNEUSDT RVNUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet S to V
SET SHELL_CMD=python download-kline.py -s SANDUSDT SCUSDT SFPUSDT SHIBUSDT SKLUSDT SLPUSDT SNXUSDT SOLUSDT SRMUSDT STMXUSDT STORJUSDT STORMUSDT STPTUSDT STRATUSDT STRAXUSDT STXUSDT SUNUSDT SUPERUSDT SUSDUSDT SUSHIDOWNUSDT SUSHIUPUSDT SUSHIUSDT SXPDOWNUSDT SXPUPUSDT SXPUSDT SYSUSDT TCTUSDT TFUELUSDT THETAUSDT TKOUSDT TLMUSDT TOMOUSDT TORNUSDT TRBUSDT TRIBEUSDT TROYUSDT TRUUSDT TRXDOWNUSDT TRXUPUSDT TRXUSDT TUSDUSDT TVKUSDT TWTUSDT UMAUSDT UNFIUSDT UNIDOWNUSDT UNIUPUSDT UNIUSDT VENUSDT VETUSDT VIDTUSDT VITEUSDT VTHOUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

REM USDT List - Alphabet W to Z
SET SHELL_CMD=python download-kline.py -s WANUSDT WAVESUSDT WAXPUSDT WINGUSDT WINUSDT WNXMUSDT WRXUSDT WTCUSDT XECUSDT XEMUSDT XLMDOWNUSDT XLMUPUSDT XLMUSDT XMRUSDT XRPBEARUSDT XRPBULLUSDT XRPDOWNUSDT XRPUPUSDT XRPUSDT XTZDOWNUSDT XTZUPUSDT XTZUSDT XVGUSDT XVSUSDT XZCUSDT YFIDOWNUSDT YFIIUSDT YFIUPUSDT YFIUSDT YGGUSDT ZECUSDT ZENUSDT ZILUSDT ZRXUSDT -i 1m -startDate %START_DATE% -endDate %END_DATE%
echo %SHELL_CMD%
%SHELL_CMD%

SET SHELL_CMD=python merge-monthly-with-daily-files.py
echo %SHELL_CMD%
%SHELL_CMD%

REM SET SHELL_CMD=python download-kline.py -t cm -s DOGEUSD_PERP -i 1m -startDate %START_DATE% -endDate %END_DATE%
REM echo %SHELL_CMD%
REM %SHELL_CMD%
